#ifndef __RPG_RESOURCES_H__
#define __RPG_RESOURCES_H__

#define RPG_ARMOR_HELMET__IRON_CAP    "IRON CAP",     6
#define RPG_ARMOR_ARMOR__IRON_ARMOR   "IRON ARMOR",   22
#define RPG_ARMOR_SHIELD__IRON_SHIELD "IRON SHIELD",  12
#define RPG_ARMOR_GLOVE__IRON_GLOVES  "IRON GLOVES",  4
#define RPG_ARMOR_BOOTS__IRON_BOOTS   "IRON BOOTS",   4

#define RPG_WEAPON_SWORD__RUSTY_SWORD "RUSTY SWORD", RPG_WEAPON_SWORD, 10
#define RPG_WEAPON_SWORD__RUSTY_AXE   "RUSTY AXE",   RPG_WEAPON_AXE,   12

#endif
