#ifndef __RPG_RESOURCES_H__
#define __RPG_RESOURCES_H__

#define RPG_ARMOR_HELMET__IRON_CAP "IRON CAP", RPG_ARMOR_ENUM_HELMET, 6
#define RPG_ARMOR_ARMOR__IRON_ARMOR "IRON ARMOR", RPG_ARMOR_ENUM_ARMOR, 22
#define RPG_ARMOR_SHIELD__IRON_SHIELD "IRON SHIELD", RPG_ARMOR_ENUM_SHIELD, 12
#define RPG_ARMOR_GLOVE__IRON_GLOVES "IRON GLOVES", RPG_ARMOR_ENUM_GLOVES, 4
#define RPG_ARMOR_BOOTS__IRON_BOOTS "IRON BOOTS", RPG_ARMOR_ENUM_BOOTS, 4

#define RPG_WEAPON_SWORD__RUSTY_SWORD "RUSTY SWORD", RPG_WEAPON_ENUM_SWORD, 10
#define RPG_WEAPON_SWORD__RUSTY_AXE   "RUSTY AXE", RPG_WEAPON_ENUM_AXE, 12

#endif
